"""Execute official Houston entry, changing only adaptation for --mode ours.

Official mode executes the original training/loss/evaluation code verbatim.
Both modes share one pre-seed ILDA realization; source split is generated by
the original entry after utils.set_seed(1341). No target-best selection.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import sys
import numpy as np
import torch

ROOT=Path(__file__).resolve().parent
LEG=Path('/home/zhangzj26/TGRS_MLUDA-2024')
sys.path.insert(0,str(LEG))
import utils
import UtilsCMS
import config_Houston as cfg
sys.path.insert(0,str(ROOT))
from class_conditional_flow_uda import (compute_source_prototypes,compute_soft_membership,
    uncertainty_filter,classwise_sinkhorn_ot,sample_ot_pairs,bridge_classification_loss)

def sha(a): return hashlib.sha256(np.asarray(a).tobytes()).hexdigest()

@torch.no_grad()
def global_prototypes(model,train_x,train_y,target_context):
    # Cross-domain features need a target counterpart. Reuse only this epoch's
    # first already-seen target batch, cycling it for all 1260 labeled sources.
    was=model.training; model.eval()
    bn={n:b.clone() for n,b in model.named_buffers()}
    feats=[]
    try:
        for start in range(0,len(train_x),32):
            x=torch.as_tensor(train_x[start:start+32]).cuda()
            feats.append(model(x,target_context[:len(x)])[0])
        assert all(torch.equal(bn[n],b) for n,b in model.named_buffers())
        f=torch.cat(feats); y=torch.as_tensor(train_y).cuda(); proto,valid=compute_source_prototypes(f,y,7)
        # classifier posterior on the same official cross-domain feature path
        qs=[]
        for start in range(0,len(train_x),32):
            x=torch.as_tensor(train_x[start:start+32]).cuda(); qs.append(model(x,target_context[:len(x)])[3].softmax(1))
        q=torch.cat(qs); means=torch.stack([q[y==c].mean(0) for c in range(7)])
        return proto,valid,means
    finally: model.train(was)

class EpochReliability:
    """Frozen gate from the preceding epoch; counts are observations, not unique IDs."""
    def __init__(self):
        self.epoch=0
        self.previous=torch.zeros(7,dtype=torch.long)
        self.counts=torch.zeros(7,dtype=torch.long)
        self.pairs=torch.zeros(7,dtype=torch.long)
        self.seen=0
        self.batches=0
        self.qsum=torch.zeros(7,7); self.wsum=torch.zeros(7); self.kl=None; self.source_q=torch.full((7,7),1/7.)
    def begin(self,epoch):
        if epoch==self.epoch: return
        assert epoch==self.epoch+1
        if self.epoch: self.previous=self.counts.clone()
        if self.epoch and self.wsum.sum()>0:
            qt=(self.qsum/self.wsum[:,None].clamp_min(1e-8)).clamp(1e-8,1)
            qs=self.source_q.clamp(1e-8,1)
            self.kl=0.5*((qs*(qs.log()-qt.log())).sum(1)+(qt*(qt.log()-qs.log())).sum(1))
        self.epoch=epoch
        self.counts.zero_(); self.pairs.zero_(); self.seen=0; self.batches=0; self.qsum.zero_(); self.wsum.zero_()
    def observe(self,high,n):
        self.counts+=high.detach().cpu()
        self.seen+=n; self.batches+=1
    def summary(self):
        return {'gate_source_epoch':self.epoch-1,'previous_n_high':self.previous.tolist(),
                'gate':(self.previous>=4).tolist(),'n_high':self.counts.tolist(),
                'ot_pairs':self.pairs.tolist(),'target_observations':self.seen,'batches':self.batches,
                'kl':None if self.kl is None else self.kl.tolist()}

def adaptation(model,fs,ft,qt,ys,proto,valid,epoch,reliability,source_q=None,tau_kl=None):
    if source_q is not None: reliability.source_q=source_q.detach().cpu()
    reliability.begin(epoch)
    with torch.no_grad():
        r=compute_soft_membership(ft.detach(),qt.detach().softmax(1),proto,valid_classes=valid)
        high=torch.bincount(r.argmax(1)[r.max(1).values>.95],minlength=7)
        reliability.observe(high,len(ft))
        pred=r.argmax(1); conf=r.max(1).values; q=qt.softmax(1)
        reliability.qsum += torch.zeros(7,7,device='cpu').index_add_(0,pred.cpu(),(q*conf[:,None]).cpu())
        reliability.wsum += torch.zeros(7,device='cpu').index_add_(0,pred.cpu(),conf.cpu())
        keep=uncertainty_filter(r,.9)
        gate=reliability.previous>=4
        if tau_kl is not None and reliability.kl is not None: gate &= reliability.kl<=tau_kl
        gated=r.clone(); gated[:,~gate.to(r.device)]=0
        ot=classwise_sinkhorn_ot(fs.detach(),ys,ft.detach(),gated,7,filtered_mask=keep)
        assert all(torch.isfinite(v['coupling']).all() for v in ot.values())
    ps,pt,pc=sample_ot_pairs(ot,fs,ft.detach(),32)
    reliability.pairs+=torch.bincount(pc.detach().cpu(),minlength=7)
    loss=fs.sum()*0
    if len(pc): loss=bridge_classification_loss(model.fc1,ps,pt,pc,.3 if epoch<=20 else .5 if epoch<=50 else .8)
    assert torch.isfinite(loss)
    return loss

def main():
    p=argparse.ArgumentParser(); p.add_argument('--mode',choices=['prepare','official','ours'],required=True)
    p.add_argument('--reliability',choices=['count','kl05','kl10'],default='count')
    p.add_argument('--out',type=Path,default=ROOT/'runs_strict_mluda_1341'); a=p.parse_args()
    a.out=a.out.resolve(); a.out.mkdir(parents=True,exist_ok=True)
    cache=a.out/'ilda.npz'
    if a.mode=='prepare':
        assert not cache.exists(),'Do not overwrite paired preprocessing'
        s,sg=utils.load_data_houston(str(LEG/'datasets/Houston/Houston13.mat'),str(LEG/'datasets/Houston/Houston13_7gt.mat'))
        t,tg=utils.load_data_houston(str(LEG/'datasets/Houston/Houston18.mat'),str(LEG/'datasets/Houston/Houston18_7gt.mat'))
        # Exactly like official: preprocessing precedes experiment seeding.
        s,t=UtilsCMS.ILDA(s,t,cfg.pca_n,cfg.radius)
        np.savez(cache,s=s,t=t)
        return
    cached=np.load(cache)
    def paired_ilda(s,t,n,r):
        assert n==2 and r==.009
        return cached['s'].copy(),cached['t'].copy()
    UtilsCMS.ILDA=paired_ilda
    cfg.seeds=[1341]; cfg.nDataSet=1
    out=a.out/(('ours_'+a.reliability) if a.mode=='ours' else 'official'); out.mkdir(exist_ok=True)
    original=(LEG/'MLUDA_hu.py').read_text()
    code=original
    code=code.replace('    print("Training...")','    audit_split(trainX, trainY, testX, testY, feature_encoder)\n    print("Training...")')
    if a.mode=='ours':
        start=code.index('            # 0\n'); end=code.index('            # Update parameters',start)
        code=code[:start]+'''            if i == 1:
                proto, valid, source_q = global_prototypes(feature_encoder, trainX, trainY, target_data.cuda())
            (source_features, source1, _, source_outputs, source_out,
             target_features, _, target1, target_outputs, target_out) = feature_encoder(source_data.cuda(),target_data.cuda())
            cls_loss = crossEntropy(source_outputs, source_label.cuda())
            bridge_loss = adaptation(feature_encoder, source_features, target_features, target_outputs,
                                     source_label.cuda(), proto, valid, epoch, reliability, source_q,
                                     {'count':None,'kl05':.5,'kl10':1.0}[a.reliability])
            loss = cls_loss + .1 * bridge_loss
            # Keep the official progress formatter without unused adaptation.
            lmmd_loss = contrastive_loss_s = contrastive_loss_t = loss.detach()*0

'''+code[end:]
    history=[]
    def audit_split(x,y,tx,ty,model):
        manifest={'source_x':sha(x),'source_y':sha(y),'target_x':sha(tx),'target_y':sha(ty),
                  'initial_model':hashlib.sha256(b''.join(v.detach().cpu().numpy().tobytes() for v in model.state_dict().values())).hexdigest(),
                  'seed':1341,'source_counts':np.bincount(y).tolist(),'source_n':len(y),'target_n':len(ty),
                  'official_file_sha256':hashlib.sha256(original.encode()).hexdigest()}
        (out/'split.json').write_text(json.dumps(manifest,indent=2)); print('SPLIT',json.dumps(manifest),flush=True)
    reliability=EpochReliability()
    namespace={'__name__':'__main__','audit_split':audit_split,'global_prototypes':global_prototypes,'adaptation':adaptation,'reliability':reliability}
    # Epoch observer uses existing values only; no forward, RNG or optimization changes.
    code=code.replace('        train_end = time.time()',"        audit_epoch(epoch, cls_loss, loss)\n        train_end = time.time()")
    def audit_epoch(e,ce,loss):
        history.append({'epoch':e,'source_ce_last_batch':float(ce.detach()),'total_loss_last_batch':float(loss.detach())})
        if a.mode=='ours':
            assert reliability.batches==38 and reliability.seen==1216
            history[-1].update(reliability.summary())
            print('RELIABILITY',json.dumps(history[-1]),flush=True)
        (out/'history.json').write_text(json.dumps(history,indent=2))
    namespace['audit_epoch']=audit_epoch
    (out/'executed.py').write_text(code)
    os.chdir(LEG)
    exec(compile(code,str(LEG/'MLUDA_hu.py'),'exec'),namespace)
    result={'epoch':100,'oa':float(namespace['acc'][0,0]/100),'aa':float(namespace['A'][0].mean()),
            'kappa':float(namespace['k'][0,0]),'per_class':namespace['A'][0].tolist(),
            'evaluated_n':len(namespace['labels']),'oa_denominator':len(namespace['test_loader'].dataset),
            'selection':'fixed_epoch100','gpu_max_allocated':torch.cuda.max_memory_allocated()}
    torch.save({'model':namespace['feature_encoder'].state_dict(),'metrics':result},out/'epoch100.pth')
    (out/'results.json').write_text(json.dumps(result,indent=2)); print('FINAL',json.dumps(result),flush=True)

if __name__=='__main__': main()
